name = "PicoHTTPParser"
uuid = "7dfb699f-0de3-4c94-bc59-7670dfa845e2"
authors = ["AbrJA <abraham.jaimes.mx@gmail.com>"]
version = "0.1.0"

[deps]
PicoHTTPParser_jll = "c57283d8-6a1b-5748-ae95-e23eefbd933c"
StringViews = "354b36f9-a18e-4713-926e-db85100087ba"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
